site_name: HCB Developers
site_url: https://hcb-developers.anscg.net/
theme:
  name: material
  custom_dir: docs/assets/overrides
  logo: assets/logo
  favicon: assets/logo-dark.svg
  palette:
    scheme: fusiondoc-dark

  font:
    text: Phantom Sans
    code: JetBrains Mono

  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.instant
    - navigation.indexes
    - search.suggest
    - search.highlight

extra_css:
  - assets/theme/fusiondoc.css
  - assets/theme/colours.css
  - assets/theme/code.css
  - assets/theme/paragraph.css
  - assets/theme/page.css
  - assets/theme/admonition.css
  - assets/theme/404.css
  - assets/theme/api-reference.css
  - assets/theme/dev-tools.css

extra_javascript:
  - assets/scripts/smooth-scroll.js

nav:
  - Home: index.md
  - Development:
    - Development: development/index.md

  - Guides: guides/

  - API Reference:
    - API Reference: api-reference/index.md
    - V3: api-reference/v3/index.md
    - V4: api-reference/v4/index.md

  - Production: production/
  - Research: research/

markdown_extensions:
  - admonition
  - attr_list
  - meta
  - md_in_html
  - pymdownx.superfences
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.emoji
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - literate-nav
  - tags
  - meta