site_name: HCB Developers
site_url: https://hcb-developers.anscg.net/
theme:
  name: material
  custom_dir: docs/assets/overrides
  logo: assets/logo
  favicon: assets/logo-dark.svg
  palette:
    scheme: fusiondoc-dark

  font:
    text: Phantom Sans
    code: JetBrains Mono

  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.instant
    - navigation.indexes
    - search.suggest
    - search.highlight

extra_css:
  - assets/theme/fusiondoc.css
  - assets/theme/colours.css
  - assets/theme/code.css
  - assets/theme/paragraph.css
  - assets/theme/page.css
  - assets/theme/admonition.css
  - assets/theme/404.css
  - assets/theme/api-reference.css
  - assets/theme/dev-tools.css

extra_javascript:
  - assets/scripts/smooth-scroll.js

nav:
  - Home: index.md
  - Tutorials:
    - Tutorials: tutorials/index.md
    - Installing Fusion: tutorials/get-started/installing-fusion.md
    - Developer Tools: tutorials/get-started/developer-tools.md
    - Getting Help: tutorials/get-started/getting-help.md
    - Fundamentals:
      - Your First Project: tutorials/fundamentals/your-first-project.md
      - Values: tutorials/fundamentals/values.md
      - Observers: tutorials/fundamentals/observers.md
      - Computeds: tutorials/fundamentals/computeds.md
      - Scopes: tutorials/fundamentals/scopes.md
    - Tables:
      - ForValues: tutorials/tables/forvalues.md
      - ForKeys: tutorials/tables/forkeys.md
      - ForPairs: tutorials/tables/forpairs.md
    - Animation:
      - Tweens: tutorials/animation/tweens.md
      - Springs: tutorials/animation/springs.md
    - Roblox:
      - Hydration: tutorials/roblox/hydration.md
      - New Instances: tutorials/roblox/new-instances.md
      - Parenting: tutorials/roblox/parenting.md
      - Events: tutorials/roblox/events.md
      - Change Events: tutorials/roblox/change-events.md
      - Outputs: tutorials/roblox/outputs.md
    - Best Practices:
      - Components: tutorials/best-practices/components.md
      - Instance Handling: tutorials/best-practices/instance-handling.md
      - References: tutorials/best-practices/references.md
      - Callbacks: tutorials/best-practices/callbacks.md
      - State: tutorials/best-practices/state.md
      - Sharing Values: tutorials/best-practices/sharing-values.md
      - Error Safety: tutorials/best-practices/error-safety.md
      - Optimisation: tutorials/best-practices/optimisation.md

  - Examples:
    - Examples: examples/index.md
    - Cookbook:
      - examples/cookbook/index.md
      - Player List: examples/cookbook/player-list.md
      - Animated Computed: examples/cookbook/animated-computed.md
      - Fetch Data From Server: examples/cookbook/fetch-data-from-server.md
      - Light & Dark Theme: examples/cookbook/light-and-dark-theme.md
      - Button Component: examples/cookbook/button-component.md
      - Loading Spinner: examples/cookbook/loading-spinner.md
      - Drag & Drop: examples/cookbook/drag-and-drop.md
  - API Reference:
    - API Reference: api-reference/index.md
    
    - V3:
      - Endpoints: api-reference/v3/Endpoint/
      - Schema: api-reference/v3/Schema/

markdown_extensions:
  - admonition
  - attr_list
  - meta
  - md_in_html
  - pymdownx.superfences
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - toc:
      permalink: true
  - pymdownx.highlight:
      guess_lang: false

plugins:
  - search
  - literate-nav